Data Set
```{r}
# Training Set for Bikeshare
train_full<-read.csv('/Users/alexkuo85/GitHub/project/kaggle/bikeshare/train.csv')

# Test Set for Bikeshare
test_full<-read.csv('/Users/alexkuo85/GitHub/project/kaggle/bikeshare/test.csv')
attach(train_full)
```

Create 24 time dataset
```{r}
# Gets a list of train data 
train_list=list()
x=0
for (i in 1:24) {
  if( x < 10) {
      train_list[[i]] <- read.csv(paste("/Users/alexkuo85/GitHub/project/kaggle/bikeshare/data/train/train_0", x, ".csv", sep=""))
  x=x+1
  } else {
      train_list[[i]] <- read.csv(paste("/Users/alexkuo85/GitHub/project/kaggle/bikeshare/data/train/train_", x, ".csv", sep=""))
  x=x+1
  }
}

# Gets a list of test data 
test_list=list()
x=0
for (i in 1:24) {
  if( x < 10) {
      test_list[[i]] <- read.csv(paste("/Users/alexkuo85/GitHub/project/kaggle/bikeshare/data/test/test_0", x, ".csv", sep=""))
  x=x+1
  } else {
      test_list[[i]] <- read.csv(paste("/Users/alexkuo85/GitHub/project/kaggle/bikeshare/data/test/test_", x, ".csv", sep=""))
  x=x+1
  }
}

```

Histogram of Plots in time periods
```{r}
par(mfrow = c(4,4))
for(i in 1:24) {
  hist(train_list[[i]]$count,xlab="Count of Hire",main=if(i-1<10) {paste("Time 0", i-1,":00:00",sep="") }else {paste("Time ", i-1,":00:00",sep="")})
}
```

Exploratory Data Analysis
```{r}
# Plot graph time vs total no. of rentals
# x-axis = time, y-axis = count
par(mfrow = c(5,5))
for(i in 1:23) {
plot(train_list[[i]]$datetime,train_list[[i]]$count, type="b",col=c(train_list[[i]]$season), xlab=if(i<10) {paste("Time 0", i,":00:00",sep="") }else {paste("Time ", i,":00:00",sep="")} , ylab="Number of Bikes hired")
}
```

Forward Step-Wise Selection
AND
GBM (Gradient Boosting Method)
```{r}
library(leaps)
library(gbm)
library(date)

# Set variables
set.seed(111) # Random for bag.fraction 
ntrees = 5000
shrinkage = 0.001
depth=9

# Aggregate how many people share bike in certain time in day of the week
#aggregate(train_list[[i]]$count,list(train_list[[i]]$day),mean)

result_list=list()
train_err=rep(NA,24)

for( j in 1:24) {

# Find Weekdays train set
train_list[[j]]$day <- weekdays(as.Date(train_list[[j]]$datetime))
train_list[[j]]$sunday[train_list[[j]]$day == "Sunday"] <-"1"
train_list[[j]]$sunday[train_list[[j]]$day != "Sunday"] <- "0"
train_list[[j]]$sunday<-as.numeric(train_list[[j]]$sunday)


# Find Weekdays test set
test_list[[j]]$day <- weekdays(as.Date(test_list[[j]]$datetime))
test_list[[j]]$sunday[test_list[[j]]$day == "Sunday"] <-"1"
test_list[[j]]$sunday[test_list[[j]]$day != "Sunday"] <- "0"
test_list[[j]]$sunday<-as.numeric(test_list[[j]]$sunday)

# When it is 08:00 before work bike share increases
# When it is 17:00 to 18:00  after work bike share increases

if(j==9) {
  
  train_list[[j]]$beforework[train_list[[j]]$day != "Sunday" ] <-"1"
  train_list[[j]]$beforework[train_list[[j]]$day != "Saturday" ] <-"1"
  train_list[[j]]$beforework<-as.numeric(train_list[[j]]$beforework)

  train_list[[j]]$beforework[train_list[[j]]$day == "Sunday" ] <-"0"
  train_list[[j]]$beforework[train_list[[j]]$day == "Saturday" ] <-"0"
  train_list[[j]]$beforework<-as.numeric(train_list[[j]]$beforework)
  
  test_list[[j]]$beforework[test_list[[j]]$day != "Sunday" ] <-"1"
  test_list[[j]]$beforework[test_list[[j]]$day != "Saturday" ] <-"1"
  test_list[[j]]$beforework<-as.numeric(test_list[[j]]$beforework)
  
  test_list[[j]]$beforework[test_list[[j]]$day == "Sunday" ] <-"0"
  test_list[[j]]$beforework[test_list[[j]]$day == "Saturday" ] <-"0"
  test_list[[j]]$beforework<-as.numeric(test_list[[j]]$beforework)
  
  train_list[[j]]$afterwork <-"0"
  train_list[[j]]$afterwork<-as.numeric(train_list[[j]]$afterwork)

  test_list[[j]]$afterwork <-"0"
  test_list[[j]]$afterwork<-as.numeric(test_list[[j]]$afterwork)
} 
else if(j==18 || j==19) {
  
  train_list[[j]]$afterwork[train_list[[j]]$day != "Sunday" ] <-"1"
  train_list[[j]]$afterwork[train_list[[j]]$day != "Saturday" ] <-"1"
  train_list[[j]]$afterwork<-as.numeric(train_list[[j]]$afterwork)
  
  train_list[[j]]$afterwork[train_list[[j]]$day == "Sunday" ] <-"0"
  train_list[[j]]$afterwork[train_list[[j]]$day == "Saturday" ] <-"0"
  train_list[[j]]$afterwork<-as.numeric(train_list[[j]]$afterwork)
  
  test_list[[j]]$afterwork[test_list[[j]]$day != "Sunday" ] <-"1"
  test_list[[j]]$afterwork[test_list[[j]]$day != "Saturday" ] <-"1"
  test_list[[j]]$afterwork<-as.numeric(test_list[[j]]$afterwork)
  
  test_list[[j]]$afterwork[test_list[[j]]$day == "Sunday" ] <-"0"
  test_list[[j]]$afterwork[test_list[[j]]$day == "Saturday" ] <-"0"
  test_list[[j]]$afterwork<-as.numeric(test_list[[j]]$afterwork)
  
  train_list[[j]]$beforework <-"0"
  train_list[[j]]$beforework<-as.numeric(train_list[[j]]$beforework)  
  
  test_list[[j]]$beforework <-"0"
  test_list[[j]]$beforework<-as.numeric(test_list[[j]]$beforework)
  
  train_list[[j]]$afterwork <-"0"
  train_list[[j]]$afterwork<-as.numeric(train_list[[j]]$afterwork)

  test_list[[j]]$afterwork <-"0"
  test_list[[j]]$afterwork<-as.numeric(test_list[[j]]$afterwork)
  
} else {
  
  train_list[[j]]$beforework <-"0"
  train_list[[j]]$beforework<-as.numeric(train_list[[j]]$beforework)  
  
  test_list[[j]]$beforework <-"0"
  test_list[[j]]$beforework<-as.numeric(test_list[[j]]$beforework)
  
  train_list[[j]]$afterwork <-"0"
  train_list[[j]]$afterwork<-as.numeric(train_list[[j]]$afterwork)

  test_list[[j]]$afterwork <-"0"
  test_list[[j]]$afterwork<-as.numeric(test_list[[j]]$afterwork)

}

attach(train_list[[j]])

regfit.fwd=regsubsets(count~beforework+afterwork+sunday+season+holiday+workingday+weather+temp+atemp+humidity+windspeed,data=train_list[[j]],nvmax=11,method="forward")

reg.summary=summary(regfit.fwd)

max_var<-which.max(reg.summary$adjr2)

fwd_reg=rep(NA,(max_var-1))
x=2
for( i in 1:max_var) {
    # Create array of variables
    fwd_reg[i]<-names(coef(regfit.fwd,max_var))[x]
    x=x+1
}

fmla<-as.formula(paste("count ~ ", paste(fwd_reg, collapse= "+")))

gbm0<-gbm(fmla, data = train_list[[j]], train.fraction = 1, interaction.depth = depth, shrinkage = shrinkage, n.trees = ntrees, bag.fraction = 0.5, cv.folds = 10, distribution = "gaussian", verbose = T, n.cores=2,n.minobsinnode=10)

rm(fmla)

# Cross Validation
best.iter_CV <- gbm.perf(gbm0, method = "cv")
train_err[j]<-gbm0$train.error[best.iter_CV]

yhat.boost<-predict(gbm0,test_list[[j]],best.iter_CV)

# Create data.frame for predicted results and timestamp
result<- as.data.frame(round(yhat.boost))
time<-as.data.frame(test_list[[j]]$datetime)

bind_result<-cbind(time,result)
names(bind_result)=c("datetime","count")

bind_result[order(bind_result$datetime),]

# row bind results together from test set
result_list=rbind(result_list,bind_result)

}


#Output to csv file
write.csv(result_list[order(as.Date(result_list$datetime, "%Y-%m-%d")),], file = "/Users/alexkuo85/GitHub/project/kaggle/bikeshare/results.csv")

```




```{r}
# Score:1.41765 Rank:1984  01/02/2015 

# Score:1.41760 Rank:1944  01/02/2015 Add interaction effect with temp and season

# Score:1.32251 Rank:1887  03/02/2015 Add forward selection with gbm, Train Error: 21299.9 , iter_CV: 6

# Score:1.32204 Rank:1886  03/02/2015 Add forward selection with gbm, Train Error: 21301.29 , iter_CV: 6

# Score:0.69750 Rank:1550  05/02/2015 Add forward selection with gbm with time slice comparison, Train Error: avg 1120.663 , iter_CV: 6


# Score:0.47862 Rank:666  05/02/2015 Add all variables with gbm with time slice comparison, Train Error: avg 1119.123 , iter_CV: 6

#train_err
# [1]   480.00430   207.64965   113.97855    33.79911     8.61111    47.73739   604.32317  4260.34717 11110.11803
#[10]  3063.53253  1930.36692  3537.27385  4572.82460  4877.98373  4646.82558  4876.80290  6080.68813 13225.24273
#[19] 12061.41477  6035.14077  2666.25866  2316.46822  1635.53787  1134.85420

# mean: 3730.324

# Score:0.47781 Rank:662  07/02/2015 Add forward seleciton variables with gbm with time slice comparison, , iter_CV: 6
#train_err
# [1]   489.00751   220.46928   128.75841    39.05311     8.13522    47.76798   640.08204  4938.74679 12171.17171  3667.72902
#[11]  1821.87954  3437.90235    4811.60641  4951.48373  4584.98909  4898.00689  6069.46272 12749.48550 11868.96714  5676.43607
#[21]  2596.45592  2243.69811  1626.67746  1115.65304

# mean: 3783.484


# Score:0.47364 Rank:628  10/02/2015 Add forward seleciton variables with sunday variable in gbm with time slice comparison, , results_output7.csv
#train_err
# [1]   489.007511   199.748723   108.999238    32.138187     8.185293    47.767978   627.449628  4938.746788
# [9] 11972.183139  3598.077958  1821.879539  3517.893771  4811.606410  4985.212510  4633.523994  4933.560014
#[17]  6069.462718 12749.485497 11868.967144  5679.508601  2569.295246  2144.386539  1475.801401   901.939514

# mean: 3757.701
```